name: Deploy VitePress site to Pages

on:
  push:
    branches:
      - "main" # Set a branch name to trigger deployment
  pull_request:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          # GitHub Actions runner automatically creates a GITHUB_TOKEN secret to use in your workflow
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist